- name: Install epel-release
  yum: name=epel-release state=installed
  become: yes
  tags:
    - packages

- name: Install common packages
  yum: name={{ item }} state=installed
  become: yes
  with_items:
    - git
    - vim
    - python-pip
    - rsync
    - wget
    - bind-utils
    - rsync
    - cmake
    - "@development"
  tags:
    - packages
