- name: Add the Erlang solution yum repository 
  yum: name=http://packages.erlang-solutions.com/erlang-solutions-1.0-1.noarch.rpm state=present
  become: yes
  tags:
    - erlang

- name: Install Erlang
  yum: name=erlang state=present
  become: yes
  tags:
    - erlang

- name: Install Rebar3
  get_url: url=https://s3.amazonaws.com/rebar3/rebar3 dest=/usr/local/bin/rebar3 mode=0755
  become: yes
  tags:
    - erlang
