- name: Install NodeJS
  yum: name={{ item }} state=installed
  become: yes
  with_items:
    - nodejs
    - npm
  tags:
    - nodejs

- name: Install coffee-script
  npm: name=coffee-script global=yes
  become: yes